name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1 # https://github.com/marketplace/actions/setup-mysql
        with:
          host port: 3306
          container port: 3306
          character set server: utf8mb4
          collation server: utf8mb4_bin
          mysql version: 8.0.23
          mysql database: topa_test
          mysql root password: root
          mysql user: user
          mysql password: root
      
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=localhost --password=root; do
            sleep 2
          done

