name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          TZ: Asia/Tokyo
          MYSQL_DATABASE: topa_test
          MYSQL_USER: user
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:

      - name: Setup Mysql
        run: |
          mysql --host 127.0.0.1 --port 3306 -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mysql --host 127.0.0.1 --port 3306 -proot -e "SET GLOBAL collation_server = 'utf8mb4_bin'"

      - name: check ping
        run: |
          mysql --host=127.0.0.1 --user=user --password=root -e "show variables like 'chara%'"
