name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0.23'
          root-password: root
          my-cnf: |
            [mysqld]
            character-set-server=utf8mb4
            collation-server=utf8mb4_general_ci
            sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
            [client]
            default-character-set=utf8mb4

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --password=root; do
            sleep 2
          done

