name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1 # https://github.com/marketplace/actions/setup-mysql
        with:
          mysql root password: root
      
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --password=root; do
            sleep 2
          done

